// Shared content and SEO data. Imported by src/App.tsx (runtime) and vite.config.ts (build-time static HTML).
// Keeping a single source means visible page text, meta tags and JSON-LD cannot drift apart.

export type Locale = 'hu' | 'en'
export type Route = 'home' | 'brands' | 'service' | 'references' | 'contact' | 'metso' | 'mj' | 'mfl' | 'outotec' | 'metsoService' | 'metsoParts' | 'mjService' | 'mjParts' | 'mflService' | 'mflParts' | 'outotecService' | 'outotecParts'
export type Pair = [string, string]
export const tx = (locale: Locale, hu: string, en: string) => locale === 'en' ? en : hu
export const paths: Record<Locale, Record<Route, string>> = {
  hu: { home: '/', brands: '/markak/', service: '/szerviz/', references: '/referenciak/', contact: '/kapcsolat/', metso: '/metso/', mj: '/mj-recycling/', mfl: '/mfl/', outotec: '/outotec/', metsoService: '/metso/szerviz/', metsoParts: '/metso/alkatresz/', mjService: '/mj-recycling/szerviz/', mjParts: '/mj-recycling/alkatresz/', mflService: '/mfl/szerviz/', mflParts: '/mfl/alkatresz/', outotecService: '/outotec/szerviz/', outotecParts: '/outotec/alkatresz/' },
  en: { home: '/en/', brands: '/en/brands/', service: '/en/service-retrofit/', references: '/en/references/', contact: '/en/contact/', metso: '/en/metso/', mj: '/en/mj-recycling/', mfl: '/en/mfl/', outotec: '/en/outotec/', metsoService: '/en/metso/service/', metsoParts: '/en/metso/parts/', mjService: '/en/mj-recycling/service/', mjParts: '/en/mj-recycling/parts/', mflService: '/en/mfl/service/', mflParts: '/en/mfl/parts/', outotecService: '/en/outotec/service/', outotecParts: '/en/outotec/parts/' },
}
export const meta: Record<Locale, Record<Route, Pair>> = {
  hu: {
    home: ['Geinvest Kft. | Bányászati gépalkatrészek és ipari szerviz', 'Bányászati, kőfeldolgozó és hulladék-újrahasznosító gépalkatrészek, ipari gépszerviz, hardfacing és PLC/CAN retrofit a Geinvest Kft.-től.'],
    brands: ['Márkák és technológiák | Geinvest Kft.', 'Metso, M&J Recycling, MFL és Outotec berendezések, alkatrészellátás és magyarországi műszaki támogatás a Geinvest Kft.-től.'],
    service: ['Ipari gépszerviz és retrofit | Geinvest Kft.', 'Helyszíni ipari gépszerviz, hibakeresés, mechanikus, hidraulikus és villamos javítás, valamint PLC és CAN retrofit.'],
    references: ['Gépipari szervizreferenciák | Geinvest Kft.', 'Geinvest szerviz-, hardfacing- és vezérléskorszerűsítési munkák ipari és hulladékfeldolgozó berendezéseken.'],
    contact: ['Kapcsolat | Geinvest Kft.', 'Kapcsolat a Geinvest Kft.-vel bányászati gépalkatrészek, ipari gépszerviz, hardfacing és retrofit ügyében.'],
    metso: ['Metso törőgép szerviz és alkatrész | Geinvest Kft.', 'Metso pofás, kúpos, HSI és VSI törőgép szerviz és alkatrészellátás Magyarországon: helyszíni javítás, karbantartás és kopóalkatrész beszerzés.'],
    mj: ['M&J Recycling aprítógép szerviz és hardfacing | Geinvest', 'M&J Recycling elő- és finomaprítók szervize, karbantartása, alkatrészellátása és vágóasztalok hardfacing feltöltő hegesztése Magyarországon.'],
    mfl: ['MFL törőgép szerviz és alkatrész | Geinvest Kft.', 'Korábbi MFL – Maschinenfabrik Liezen – törőgépek javítása, szervize és alkatrészellátása Magyarországon, pontos gépazonosítás alapján.'],
    outotec: ['Outotec szerviz és alkatrészellátás | Geinvest Kft.', 'Outotec berendezések magyarországi szervize: karbantartás, hibakeresés, javítás és alkatrészellátás a Geinvest Kft. műszaki hátterével.'],
    metsoService: ['Metso törőgép javítás és karbantartás | Geinvest', 'Helyszíni Metso törőgép javítás és karbantartás: hibakeresés, mechanikus, hidraulikus és villamos szerviz, PLC és CAN diagnosztika Magyarországon.'],
    metsoParts: ['Metso alkatrész és kopóalkatrész | Geinvest Kft.', 'Metso törőgép alkatrész és kopóalkatrész azonosítása és beszerzése: törőpofa, kúpköpeny, ütőléc és rostafelület. Küldje el a gép adatait.'],
    mjService: ['M&J aprítógép javítás és hardfacing | Geinvest', 'M&J Recycling aprítógép javítás, megelőző karbantartás és vágóasztal hardfacing feltöltő hegesztés gyártói szervizképzéssel Magyarországon.'],
    mjParts: ['M&J Recycling alkatrész és kések | Geinvest Kft.', 'M&J Recycling előaprító és finomaprító alkatrész: kések, vágóasztal-elemek és kopóbetétek azonosítása és beszerzése Magyarországon.'],
    mflService: ['MFL törőgép javítás és felújítás | Geinvest Kft.', 'Régi MFL törőgépek javítása, felújítása és vezérléskorszerűsítése Magyarországon, helyszíni felmérés és pontos gépazonosítás alapján.'],
    mflParts: ['MFL törőgép alkatrész beszerzés | Geinvest Kft.', 'MFL törőgép alkatrész és kopóalkatrész azonosítása mintadarab, típustábla és felmérés alapján, hiányos dokumentáció esetén is.'],
    outotecService: ['Outotec szerviz és karbantartás | Geinvest Kft.', 'Outotec berendezések helyszíni szervize Magyarországon: karbantartás, hibakeresés, mechanikus, hidraulikus és villamos javítás.'],
    outotecParts: ['Outotec alkatrész beszerzés | Geinvest Kft.', 'Outotec alkatrész és kopóalkatrész felmérése és beszerzése a berendezés gyári azonosítása alapján, magyarországi műszaki háttérrel.'],
  },
  en: {
    home: ['Geinvest Kft. | Mining Machinery Parts and Industrial Service', 'Mining, quarrying and waste-recycling machinery parts, industrial service, hardfacing and PLC/CAN retrofit from Geinvest Kft.'],
    brands: ['Brands and Technologies | Geinvest Kft.', 'Metso, M&J Recycling, MFL and Outotec equipment, parts supply and technical support from Geinvest Kft.'],
    service: ['Industrial Equipment Service and Retrofit | Geinvest Kft.', 'On-site industrial equipment service, troubleshooting, mechanical, hydraulic and electrical repairs, plus PLC and CAN retrofit.'],
    references: ['Industrial Service References | Geinvest Kft.', 'Geinvest service, hardfacing and control-system modernisation work on industrial and waste-processing equipment.'],
    contact: ['Contact | Geinvest Kft.', 'Contact Geinvest Kft. about mining machinery parts, industrial equipment service, hardfacing and retrofit.'],
    metso: ['Metso Crusher Service and Parts | Geinvest Kft.', 'Technical support, repair and parts supply for Metso jaw, cone, HSI and VSI crushing equipment in Hungary.'],
    mj: ['M&J Recycling Service and Hardfacing | Geinvest Kft.', 'Service, maintenance, parts supply and hardfacing for M&J Recycling pre-shredders and fine-shredders.'],
    mfl: ['MFL Crusher Service and Parts | Geinvest Kft.', 'Repair, service and parts supply for legacy MFL mineral-processing and crushing equipment in Hungary.'],
    outotec: ['Outotec Equipment Service and Parts | Geinvest Kft.', 'Technical support, repair, parts supply and comprehensive service for Outotec equipment in Hungary.'],
    metsoService: ['Metso Crusher Repair and Maintenance | Geinvest', 'On-site Metso crusher repair and maintenance: troubleshooting, mechanical, hydraulic and electrical service, PLC and CAN diagnostics in Hungary.'],
    metsoParts: ['Metso Crusher Parts and Wear Parts | Geinvest', 'Identification and sourcing of Metso crusher parts and wear parts: jaw plates, mantles and concaves, blow bars and screening surfaces.'],
    mjService: ['M&J Shredder Repair and Hardfacing | Geinvest', 'M&J Recycling shredder repair, preventive maintenance and cutting-table hardfacing rebuild welding, backed by manufacturer service training.'],
    mjParts: ['M&J Recycling Parts and Knives | Geinvest Kft.', 'Identification and supply of M&J Recycling pre-shredder and fine-shredder parts: knives, cutting-table components and wear inserts.'],
    mflService: ['MFL Crusher Repair and Refurbishment | Geinvest', 'Repair, refurbishment and control-system modernisation of legacy MFL crushers, based on on-site survey and exact machine identification.'],
    mflParts: ['MFL Crusher Parts Sourcing | Geinvest Kft.', 'Identification of MFL crusher parts and wear parts from a sample, nameplate and survey, even where documentation is incomplete.'],
    outotecService: ['Outotec Service and Maintenance | Geinvest Kft.', 'On-site service for Outotec equipment in Hungary: maintenance, troubleshooting, mechanical, hydraulic and electrical repair.'],
    outotecParts: ['Outotec Parts Sourcing | Geinvest Kft.', 'Assessment and sourcing of Outotec parts and wear parts based on factory identification of the equipment, with Hungarian technical support.'],
  },
}
export const origin = 'https://geinvestkft.com'
export const phone = '+36 20 951 4799'
export const email = 'gaszner@geinvestkft.com'

export type Faq = { q: Pair; a: Pair }
export const faqs: Partial<Record<Route, Faq[]>> = {
  metso: [
    { q: ['Vállalnak Metso törőgép szervizt Magyarországon?', 'Do you service Metso crushers in Hungary?'], a: ['Igen. Helyszíni hibakeresést, megelőző karbantartást, valamint mechanikus, hidraulikus, villamos és vezérléstechnikai javítást is végzünk Metso törőberendezéseken.', 'Yes. We carry out on-site troubleshooting, preventive maintenance and mechanical, hydraulic, electrical and control-system repairs on Metso crushing equipment.'] },
    { q: ['Milyen Metso törőtípusokhoz tudnak segíteni?', 'Which Metso crusher types can you support?'], a: ['Pofás, kúpos, vízszintes tengelyű (HSI) és függőleges tengelyű (VSI) röpítőtörőkhöz, stacionárius és mobil kivitelben egyaránt. A Metso kínálatában a Nordberg® C Series™ pofás, valamint a GP és HP kúpos családok is megtalálhatók.', 'Jaw, cone, horizontal shaft impact (HSI) and vertical shaft impact (VSI) crushers, in both stationary and mobile configurations. Metso’s portfolio includes the Nordberg® C Series™ jaw crushers and the GP and HP cone families.'] },
    { q: ['Tudnak Metso kopóalkatrészt beszerezni?', 'Can you source Metso wear parts?'], a: ['Az alkatrészigényt a gép típustáblája, gyári száma és a keresett elem cikkszáma vagy fotója alapján azonosítjuk, majd erre adunk ajánlatot. Törőgépeken tipikusan törőpofák, kúpköpenyek, ütőlécek és rostafelületek kopnak a leggyorsabban.', 'We identify the parts requirement from the machine nameplate, serial number and the part number or a photo, then quote on that basis. On crushers the fastest-wearing items are typically jaw plates, mantles and concaves, blow bars and screening surfaces.'] },
    { q: ['Mobil és stacionárius Metso gépet is szervizelnek?', 'Do you service both mobile and stationary Metso machines?'], a: ['Igen. A Metso több törőcsaládot stacionárius, hordozható és mobil kivitelben is kínál, és mindhárom esetben a teljes rendszert vizsgáljuk: mechanika, hidraulika, villamosság és vezérléstechnika együtt.', 'Yes. Metso offers several crusher families in stationary, portable and mobile configurations, and in each case we assess the complete system: mechanics, hydraulics, electrics and controls together.'] },
    { q: ["Milyen gyorsan tudnak reagálni Metso üzemzavar esetén?", "How quickly can you respond to a Metso breakdown?"], a: ["A bejelentés után egyeztetjük a kiszállás időpontját. A határidőt a hiba jellege, a szükséges kopóalkatrészek elérhetősége és a szervizcsapat leterheltsége együtt határozza meg.", "We agree the site visit once the fault is reported. The lead time depends on the nature of the fault, the availability of the required wear parts and the service team’s workload."] },
    { q: ["Milyen adatokkal tudnak a leggyorsabban Metso ajánlatot adni?", "What data lets you quote fastest on a Metso machine?"], a: ["A törő típustáblája vagy gyári száma, a törési fokozat, az üzemóra, valamint a keresett alkatrész cikkszáma vagy fotója. Ezekkel az azonosítás általában egy körben lezárható.", "The crusher nameplate or serial number, the crushing stage, operating hours and the part number or a photo of the required item. With these, identification can usually be completed in one round."] },
  ],
  mj: [
    { q: ['Vállalnak M&J Recycling aprítógép szervizt?', 'Do you service M&J Recycling shredders?'], a: ['Igen. Négyfős, műszaki végzettségű szervizcsapatunk közvetlenül az M&J Recycling dániai szakembereinél szerzett gyártói képzést, és a megelőző karbantartástól a hibakeresésen át a mechanikus, hidraulikus, villamos és vezérléstechnikai javításig teljes körű szervizt nyújtunk.', 'Yes. Our four-person, technically qualified service team completed manufacturer training directly with M&J Recycling specialists in Denmark, and we provide comprehensive service from preventive maintenance and troubleshooting through to mechanical, hydraulic, electrical and control-system repairs.'] },
    { q: ['Mit jelent a vágóasztal és a kések hardfacing feltöltő hegesztése?', 'What does hardfacing of cutting tables and knives involve?'], a: ['A hardfacing feltöltő hegesztés során a kopott felületre kemény, kopásálló réteget hegesztünk fel, így az alkatrész geometriája helyreállítható teljes csere nélkül. Ez az M&J vágóasztalok és kések esetében kiemelt szakterületünk, többéves gyakorlati tapasztalattal.', 'Hardfacing rebuild welding deposits a hard, wear-resistant layer onto the worn surface, restoring the component geometry without full replacement. This is a core area of expertise for us on M&J cutting tables and knives, backed by several years of practical experience.'] },
    { q: ['Tudnak M&J előaprító és finomaprító alkatrészt szállítani?', 'Can you supply M&J pre-shredder and fine-shredder parts?'], a: ['Igen. A kések, vágóasztal-elemek, kopóbetétek és gépészeti alkatrészek igényét a gép típusa, gyári száma és a keresett elem alapján azonosítjuk, és ez alapján adunk ajánlatot.', 'Yes. We identify requirements for knives, cutting-table components, wear inserts and mechanical parts from the machine type, serial number and the specific item, and quote on that basis.'] },
    { q: ['Mi az M&J eDrive, és milyen előnye van?', 'What is M&J eDrive and what is the benefit?'], a: ['Az eDrive előaprítók a hagyományos hidraulikus hajtás helyett elektromos hajtásláncot használnak. A gyártó P4000e oldala akár 80% energia-megtakarítást ad meg a hidraulikus aprítókhoz képest, a ReCapture rendszerre pedig további, akár 25%-os megtakarítást jelöl meg. Ezek gyártói adatok.', 'eDrive pre-shredders use an electric drivetrain instead of conventional hydraulic drive. The manufacturer’s P4000e page states up to 80% energy savings compared with hydraulic shredders, and a further saving of up to 25% for the ReCapture system. These are manufacturer figures.'] },
    { q: ['Milyen hulladékáramokhoz használhatók az M&J aprítók?', 'Which waste streams are M&J shredders used for?'], a: ['Kommunális, ipari, fa-, építési és egyéb hulladékáramok elő- és finomaprításához, többek között RDF/SRF előállításához. A megfelelő folyamat kialakításánál az anyagösszetétel, az elvárt frakció és a további válogatási vagy hasznosítási lépés is lényeges.', 'Pre-shredding and fine-shredding of municipal, industrial, wood, construction and other waste streams, including RDF/SRF production. Material composition, the required fraction and downstream sorting or recovery steps all matter when configuring the process.'] },
    { q: ["Milyen adatok kellenek egy M&J megkereséshez?", "What data is needed for an M&J enquiry?"], a: ["Az aprító típusa és gyári száma, a feldolgozott hulladékáram, valamint a kopott kés vagy vágóasztal fotója. A hardfacing igény felméréséhez a kopott felület képei a leghasznosabbak.", "The shredder type and serial number, the waste stream processed, and photos of the worn knife or cutting table. For assessing a hardfacing requirement, images of the worn surface are the most useful."] },
  ],
  mfl: [
    { q: ['Tudnak régi MFL törőgéphez alkatrészt biztosítani?', 'Can you provide parts for older MFL crushers?'], a: ['Igen, de minden esetben azonosítással kezdünk. A rendelkezésre álló dokumentáció, az alkatrész mintadarabja vagy fotója, a felmért méretek és a beépítési környezet alapján határozzuk meg biztonsággal a következő lépést.', 'Yes, though we always start with identification. The available documentation, a sample or photo of the part, measured dimensions and the installation environment let us determine the right next step with confidence.'] },
    { q: ['Mi a helyzet, ha nincs meg a gép dokumentációja?', 'What if the machine documentation is missing?'], a: ['Ez a régi gépparknál gyakori. Ilyenkor a típustáblából, a helyszíni felmérésből, a kopott alkatrész mintadarabjából és a beépítési helyről készült fotókból indulunk ki, és ezekből építjük fel a szükséges műszaki adatokat.', 'This is common with older fleets. In that case we work from the nameplate, an on-site survey, a sample of the worn part and photos of the installation point, and build up the required technical data from those.'] },
    { q: ['Az MFL és az SBM ugyanaz a termékkör?', 'Are MFL and SBM the same product range?'], a: ['Nem. Ezen az oldalon kifejezetten a régi Maschinenfabrik Liezen – MFL – berendezésekről van szó, nem az SBM mai termékportfóliójáról. A Maschinenfabrik Liezen und Gießerei osztrák gépgyártó és öntödei vállalat, amely Liezenben működik.', 'No. This page specifically concerns older Maschinenfabrik Liezen — MFL — equipment, not the current SBM product portfolio. Maschinenfabrik Liezen und Gießerei is an Austrian engineering and foundry company based in Liezen.'] },
    { q: ['Érdemes a régi MFL gépet javítani, vagy inkább cserélni?', 'Is it worth repairing an older MFL machine or replacing it?'], a: ['Ha a mechanika még jó állapotban van, a javítás és a vezérléskorszerűsítés gyakran gazdaságosabb a gépcserénél. Az állapotfelmérés után reális képet adunk arról, mi javítható és mi az, aminél a csere indokolt.', 'If the mechanics are still sound, repair and control-system modernisation are often more economical than replacement. After a condition assessment we give a realistic picture of what can be repaired and where replacement is justified.'] },
    { q: ['Vállalnak MFL gépen vezérléskorszerűsítést?', 'Do you carry out control-system modernisation on MFL machines?'], a: ['Igen. Régi mobil és stacionárius berendezéseknél részleges vagy teljes retrofitot is vállalunk: PLC, kezelői kijelző, I/O rendszer, szenzorika, kábelezés és CAN-alapú kommunikáció korszerűsítését.', 'Yes. For older mobile and stationary equipment we carry out partial or complete retrofits: PLC, operator display, I/O system, sensors, wiring and CAN-based communication.'] },
    { q: ["Milyen adatokból tudnak elindulni egy régi MFL gépnél?", "What data lets you start work on an older MFL machine?"], a: ["A típustábla fotója és a gyári szám a kiindulópont. Ha ezek már nem olvashatók, a helyszíni felmérés, a kopott alkatrész mintadarabja és a beépítési helyről készült képek alapján dolgozunk.", "A photo of the nameplate and the serial number are the starting point. Where these are no longer legible we work from an on-site survey, a sample of the worn part and images of the installation point."] },
  ],
  outotec: [
    { q: ['Milyen Outotec berendezésekhez nyújtanak támogatást?', 'Which Outotec equipment do you support?'], a: ['Az Outotec névhez kötődő technológiák tipikusan ásványfeldolgozási és anyagkezelési feladatokban jelennek meg. A támogatás megkezdése előtt a berendezés konkrét termékcsoportját, gyári azonosítóját és az üzemi feladatot tisztázzuk.', 'Technologies associated with the Outotec name are typically used in mineral-processing and material-handling duties. Before starting, we establish the specific product group, factory identification and operating duty.'] },
    { q: ['Az Outotec ma a Metso része?', 'Is Outotec now part of Metso?'], a: ['A márkanév vállalati háttere megváltozott: a Metso és az Outotec 2020-ban Metso Outotec néven egyesült, a vállalat pedig 2023-ban visszatért a Metso névhez. Nálunk az Outotec megnevezés a Geinvest képviseletéhez tartozó termékkört jelöli.', 'The corporate background changed: Metso and Outotec merged as Metso Outotec in 2020, and the company returned to the Metso name in 2023. On our site, Outotec denotes the product range represented by Geinvest.'] },
    { q: ['Tudnak Outotec alkatrészt beszerezni?', 'Can you source Outotec parts?'], a: ['Igen. Az alkatrész- és kopóalkatrész-igényt a berendezés azonosítása után, a gyári adatok és a keresett elem cikkszáma vagy fotója alapján mérjük fel, majd ez alapján adunk ajánlatot.', 'Yes. Once the equipment is identified, we assess parts and wear-parts requirements from the factory data and the part number or a photo, then quote on that basis.'] },
    { q: ['Vállalnak helyszíni Outotec szervizt Magyarországon?', 'Do you provide on-site Outotec service in Hungary?'], a: ['Igen. A Geinvest az Outotec termékekhez karbantartást, hibakeresést és javítást is biztosít, a mechanikus és hidraulikus munkáktól a villamos és vezérléstechnikai feladatokig.', 'Yes. Geinvest provides maintenance, troubleshooting and repair for Outotec products, from mechanical and hydraulic work through to electrical and control-system tasks.'] },
    { q: ["Mennyi idő alatt tudnak Outotec berendezéshez kiszállni?", "How soon can you attend an Outotec machine?"], a: ["A kiszállást a berendezés azonosítása után tudjuk ütemezni, mert ez határozza meg a szükséges szakembert és alkatrészeket. A konkrét időpontot minden esetben visszaigazoljuk.", "We can schedule the visit once the equipment is identified, as this determines the specialists and parts required. We always confirm a specific date."] },
    { q: ["Milyen adatokat kérnek egy Outotec megkeresés indításához?", "What data do you need to open an Outotec enquiry?"], a: ["A berendezés termékcsoportja és gyári azonosítója, az üzemi feladat, valamint a keresett alkatrész cikkszáma vagy fotója. Ezek nélkül a termékkör nem határozható meg biztonsággal.", "The product group and factory identification of the equipment, the operating duty, and the part number or a photo of the required item. Without these the product range cannot be established reliably."] },
  ],
  metsoService: [
    { q: ['Kiszállnak helyszíni Metso javításra?', 'Do you travel to site for Metso repairs?'], a: ['Igen, a szerviz nagy része helyszínen zajlik. A kiszállás előtt a gép adatai és a hibaleírás alapján összeállítjuk a szükséges szerszámokat és a valószínűsíthető alkatrészeket.', 'Yes, most of our service work is carried out on site. Before travelling we assemble the necessary tools and the parts likely to be needed, based on the machine data and fault description.'] },
    { q: ['Végeznek megelőző karbantartást is, nem csak hibajavítást?', 'Do you also carry out preventive maintenance, not just repairs?'], a: ['Igen. Az állapotfelmérés során azonosítjuk a várható hibákat és a kopóalkatrészeket, így a leállás tervezhetővé válik a váratlan üzemzavar helyett.', 'Yes. During condition assessment we identify likely faults and wear parts, which makes downtime plannable instead of unexpected.'] },
    { q: ['Tudnak PLC- és CAN-hibát is keresni a törőn?', 'Can you also diagnose PLC and CAN faults on the crusher?'], a: ['Igen. PLC-vezérlés, I/O, valamint CAN, CANopen és J1939 kommunikáció diagnosztikáját és szoftveres hibakeresését is vállaljuk, nem csak a gépészeti részt.', 'Yes. We cover PLC controls, I/O and CAN, CANopen and J1939 communication diagnostics and software troubleshooting, not only the mechanical side.'] },
    { q: ["Mennyi idő alatt tudnak kiszállni törőgép leállás esetén?", "How soon can you attend a crusher stoppage?"], a: ["A kiszállás időpontját a bejelentés után egyeztetjük. Mivel a szükséges alkatrészeket előre összeállítjuk, a pontos határidő a hiba jellegétől és az alkatrészek elérhetőségétől függ.", "We agree the visit once the stoppage is reported. Because we assemble the required parts in advance, the exact lead time depends on the nature of the fault and part availability."] },
  ],
  metsoParts: [
    { q: ['Honnan tudják, melyik alkatrész illik a gépembe?', 'How do you determine which part fits my machine?'], a: ['A gép típustáblája és gyári száma, valamint a keresett elem cikkszáma vagy fotója alapján. Ugyanaz a gépcsalád több kivitelben is előfordul, ezért ezek nélkül nagy a hibás rendelés kockázata.', 'From the machine nameplate and serial number together with the part number or a photo. The same crusher family exists in several configurations, so without these the risk of ordering the wrong item is high.'] },
    { q: ['Csak kopóalkatrészt tudnak szállítani?', 'Do you only supply wear parts?'], a: ['Nem. A kopóelemeken túl gépészeti alkatrészeket, csapágyakat, tömítéseket és hajtáselemeket, valamint hidraulikus és villamos elemeket is beszerzünk.', 'No. Beyond wear items we also source mechanical components, bearings, seals and drive elements, as well as hydraulic and electrical parts.'] },
    { q: ['Érdemes lehet a kopott alkatrészt felújítani?', 'Might it be worth refurbishing a worn part?'], a: ['Bizonyos kopófelületek feltöltő hegesztéssel helyreállíthatók, ami gyorsabb és költséghatékonyabb lehet a teljes cserénél. Az állapot ismeretében adunk erre javaslatot.', 'Some wear surfaces can be restored by rebuild welding, which may be faster and more economical than full replacement. We advise on this once the condition is known.'] },
    { q: ["Mennyi idő egy Metso alkatrész beazonosítása?", "How long does identifying a Metso part take?"], a: ["Ha a típustábla, a gyári szám és a keresett elem fotója rendelkezésre áll, az azonosítás jellemzően rövid. Hiányos adatok esetén helyszíni felmérés vagy méretfelvétel is szükséges lehet.", "With the nameplate, serial number and a photo of the item available, identification is typically quick. Where data is incomplete, an on-site survey or dimensional check may also be needed."] },
  ],
  mjService: [
    { q: ['Mennyi ideig tart egy vágóasztal hardfacing felújítása?', 'How long does a cutting-table hardfacing rebuild take?'], a: ['A ráfordítás a kopás mértékétől és a felület méretétől függ, ezért a felmérés után adunk konkrét időbecslést. A tervezhetőség érdekében a felújítást általában karbantartási leálláshoz igazítjuk.', 'The effort depends on the extent of wear and the size of the surface, so we give a specific estimate after assessment. To keep it plannable we usually align the rebuild with a maintenance shutdown.'] },
    { q: ['Az eDrive gépek villamos hajtásláncához is értenek?', 'Are you familiar with the electric drivetrain on eDrive machines?'], a: ['Igen. A villamos és vezérléstechnikai javítás a szolgáltatásunk része, így az elektromos hajtású gépeknél sem külön szolgáltatóhoz kell fordulni.', 'Yes. Electrical and control-system repair is part of our service, so electric-drive machines do not require a separate provider.'] },
    { q: ['Vállalnak rendszeres karbantartási ütemezést?', 'Do you take on a regular maintenance schedule?'], a: ['A megelőző karbantartás ütemezését az üzemórák és a feldolgozott anyag alapján egyeztetjük. A konkrét feltételeket minden esetben egyedileg beszéljük meg.', 'We agree the preventive maintenance schedule based on operating hours and the processed material. Specific terms are always discussed individually.'] },
    { q: ["Mennyi idő alatt tudnak reagálni aprítógép leállásra?", "How soon can you respond to a shredder stoppage?"], a: ["A bejelentés után egyeztetjük a kiszállást. Mivel a hulladékfeldolgozásban a leállás gyorsan feltorlódást okoz, a hibaleírás és néhány fotó alapján előre felkészülünk a valószínű javításra.", "We agree the visit once the stoppage is reported. As downtime in waste processing quickly causes a backlog, we prepare for the likely repair in advance from the fault description and a few photos."] },
  ],
  mjParts: [
    { q: ['Milyen adat kell egy M&J késrendeléshez?', 'What data is needed to order M&J knives?'], a: ['A gép típusa és gyári száma, a kés pozíciója, valamint a meglévő kés cikkszáma vagy méretezett fotója. Ezek alapján azonosítjuk a megfelelő kivitelt.', 'The machine type and serial number, the knife position and the part number or a dimensioned photo of the existing knife. These let us identify the correct version.'] },
    { q: ['Új kés vagy felújítás gazdaságosabb?', 'Is a new knife or a rebuild more economical?'], a: ['Ez a kopás mértékétől függ. A felmérés után megmondjuk, hogy a hardfacing feltöltő hegesztés vagy az új alkatrész beépítése a jobb megoldás az adott elemnél.', 'It depends on the extent of wear. After assessment we advise whether hardfacing rebuild welding or a new part is the better option for that item.'] },
    { q: ['Szállítanak hegesztőanyagot is a helyreállításhoz?', 'Do you also supply welding consumables for restoration?'], a: ['A hardfacing munkát általában mi végezzük, de a kopásálló hegesztőanyagok igényét is fel tudjuk mérni, ha a helyreállítás saját műhelyben történik.', 'We usually carry out the hardfacing work ourselves, but we can also assess wear-resistant welding consumable requirements if the restoration is done in your own workshop.'] },
    { q: ["Tudnak teljes késkészletet egyszerre szállítani?", "Can you supply a complete set of knives at once?"], a: ["Igen, az igényt a gép típusa és a késpozíciók alapján mérjük fel. Teljes készlet cseréjénél a vágóasztal állapotát is érdemes egyszerre megvizsgálni.", "Yes, we assess the requirement from the machine type and knife positions. When replacing a full set it is worth inspecting the cutting table condition at the same time."] },
  ],
  mflService: [
    { q: ['Megnézik a gépet a helyszínen, mielőtt ajánlatot adnak?', 'Do you inspect the machine on site before quoting?'], a: ['Régi MFL berendezésnél ez a legbiztosabb út. A helyszíni felmérés során dokumentáljuk a meglévő kivitelt, és ezután adunk reális javítási vagy felújítási javaslatot.', 'With older MFL equipment this is the most reliable route. During the site survey we document the existing configuration and then give a realistic repair or refurbishment proposal.'] },
    { q: ['Csak a vezérlést lehet korszerűsíteni, vagy a gépészetet is?', 'Can only the controls be modernised, or the mechanics too?'], a: ['Mindkettő szóba jön. A retrofit lehet részleges, csak a vezérlésre kiterjedő, de a kopott gépészeti részegységek javítását is elvégezzük ugyanazon a gépen.', 'Both are possible. A retrofit can be partial and cover only the controls, but we also repair worn mechanical assemblies on the same machine.'] },
    { q: ['Mennyire kockázatos egy régi gépet felújítani?', 'How risky is refurbishing an older machine?'], a: ['A kockázatot az állapotfelmérés csökkenti. Ha egy részegység már nem javítható gazdaságosan, ezt előre jelezzük, nem a munka közben derül ki.', 'Condition assessment reduces the risk. If an assembly can no longer be repaired economically we flag it in advance, rather than it emerging mid-project.'] },
    { q: ["Mit érdemes előkészíteni a helyszíni felmérés előtt?", "What should be prepared before the site survey?"], a: ["Minden megmaradt dokumentációt, rajzot és korábbi javítási feljegyzést, valamint a gép hozzáférhetőségét. Ezek alapján a felmérés egy alkalommal is lezárható.", "Any surviving documentation, drawings and previous repair records, plus access to the machine. With these the survey can often be completed in a single visit."] },
  ],
  mflParts: [
    { q: ['Van esély alkatrészre, ha a gép több évtizedes?', 'Is there any chance of parts for a machine that is decades old?'], a: ['Sok esetben igen, de ez az azonosítás eredményétől függ. Előfordul, hogy katalógusból elérhető alkatrész helyett a méret alapján legyártatható vagy felújítható elem a járható út.', 'Often yes, though it depends on the outcome of identification. Sometimes an item made to measure or a refurbished part is the viable route rather than a catalogue part.'] },
    { q: ['Elég egy fotó az alkatrészről?', 'Is a photo of the part enough?'], a: ['A fotó jó kiindulás, de a biztos azonosításhoz általában méretek is szükségesek. A legjobb, ha a kopott alkatrész mintadarabja is rendelkezésre áll.', 'A photo is a good starting point, but reliable identification usually needs dimensions as well. Best of all is having the worn part available as a sample.'] },
    { q: ['Mit tesznek, ha az eredeti alkatrész már nem elérhető?', 'What happens if the original part is no longer available?'], a: ['Ilyenkor felmérjük, hogy az elem javítható, felújítható vagy méret alapján pótolható. A döntés előtt mindig tisztázzuk, milyen műszaki feltételeknek kell megfelelnie.', 'In that case we assess whether the item can be repaired, refurbished or replaced to measure. Before deciding we always clarify the technical requirements it must meet.'] },
    { q: ["Mennyi idő egy MFL alkatrész beszerzése?", "How long does sourcing an MFL part take?"], a: ["Ez az azonosítás eredményétől függ. Ha az elem méret alapján legyártatható vagy felújítható, a határidőt a gyártási vagy javítási kapacitás határozza meg, amit előre visszaigazolunk.", "This depends on the outcome of identification. If the item can be made to measure or refurbished, the lead time is set by manufacturing or repair capacity, which we confirm in advance."] },
  ],
  outotecService: [
    { q: ['Mivel kezdődik egy Outotec szervizmegkeresés?', 'How does an Outotec service enquiry begin?'], a: ['A berendezés konkrét termékcsoportjának, gyári azonosítójának és üzemi feladatának tisztázásával. Ezután tudjuk megmondani, milyen karbantartás vagy javítás indokolt.', 'By establishing the specific product group, factory identification and operating duty of the equipment. Only then can we advise which maintenance or repair is appropriate.'] },
    { q: ['A villamos és vezérlési hibákat is vállalják?', 'Do you also handle electrical and control faults?'], a: ['Igen. A mechanikus és hidraulikus munkán túl villamos javítást, valamint PLC- és CAN-diagnosztikát is végzünk.', 'Yes. Beyond mechanical and hydraulic work we also carry out electrical repair and PLC and CAN diagnostics.'] },
    { q: ['Miért szerepel még az Outotec név, ha a vállalat ma Metso?', 'Why is the Outotec name still used if the company is now Metso?'], a: ['A Metso és az Outotec 2020-ban Metso Outotec néven egyesült, majd a vállalat 2023-ban visszatért a Metso névhez. Nálunk az Outotec megnevezés a Geinvest képviseletéhez tartozó termékkört jelöli.', 'Metso and Outotec merged as Metso Outotec in 2020, and the company returned to the Metso name in 2023. On our site, Outotec denotes the product range represented by Geinvest.'] },
    { q: ["Milyen határidővel tudnak Outotec javítást vállalni?", "What lead time applies to an Outotec repair?"], a: ["A határidőt a berendezés azonosítása, a hiba jellege és az alkatrészek elérhetősége együtt adja. Ezért a felmérés után adunk konkrét, visszaigazolt időpontot.", "The lead time depends on equipment identification, the nature of the fault and part availability. We therefore give a specific, confirmed date after assessment."] },
  ],
  outotecParts: [
    { q: ['Milyen adat kell egy Outotec alkatrész-ajánlathoz?', 'What data is needed for an Outotec parts quotation?'], a: ['A berendezés gyári azonosítója és termékcsoportja, a keresett elem cikkszáma vagy fotója, valamint néhány kép a beépítési helyről.', 'The factory identification and product group of the equipment, the part number or a photo of the required item, and a few images of the installation point.'] },
    { q: ['Tudnak kopóalkatrészt is szállítani?', 'Can you supply wear parts as well?'], a: ['Igen, a kopóalkatrészek és a gépészeti alkatrészek igényét egyaránt felmérjük, majd a beazonosított elemekre adunk ajánlatot.', 'Yes, we assess both wear-part and mechanical component requirements, then quote on the identified items.'] },
    { q: ['Az alkatrészcsere mellett a hiba okát is megvizsgálják?', 'Alongside replacing the part, do you investigate the cause?'], a: ['Igen. Ha a kopás oka gépészeti vagy vezérlési probléma, az alkatrész cseréje önmagában nem tartós megoldás, ezért ezeket együtt vizsgáljuk.', 'Yes. If the wear is caused by a mechanical or control problem, replacing the part alone is not a lasting solution, so we examine them together.'] },
    { q: ["Mennyi idő az Outotec alkatrészek beszerzése?", "How long does sourcing Outotec parts take?"], a: ["A beazonosítás után tudjuk megadni. A kopóalkatrészek és a gépészeti elemek elérhetősége eltérő lehet, ezért a határidőt elemenként igazoljuk vissza.", "We can state this once identification is complete. Availability can differ between wear parts and mechanical components, so we confirm lead times item by item."] },
  ],
}
export const brandOf: Partial<Record<Route, string>> = { metso: 'Metso', mj: 'M&J Recycling', mfl: 'MFL', outotec: 'Outotec', metsoService: 'Metso', metsoParts: 'Metso', mjService: 'M&J Recycling', mjParts: 'M&J Recycling', mflService: 'MFL', mflParts: 'MFL', outotecService: 'Outotec', outotecParts: 'Outotec' }
export const parentOf: Partial<Record<Route, Route>> = { metsoService: 'metso', metsoParts: 'metso', mjService: 'mj', mjParts: 'mj', mflService: 'mfl', mflParts: 'mfl', outotecService: 'outotec', outotecParts: 'outotec' }
export const brandHubRoutes: Route[] = ['metso', 'mj', 'mfl', 'outotec']
export const partsRoutes: Route[] = ['metsoParts', 'mjParts', 'mflParts', 'outotecParts']
export const serviceRoutes: Route[] = ['metsoService', 'mjService', 'mflService', 'outotecService']
export function serviceTypeOf(route: Route, brand: string): Pair {
  if (partsRoutes.includes(route)) return [`${brand} alkatrész- és kopóalkatrész-ellátás`, `${brand} parts and wear-parts supply`]
  if (serviceRoutes.includes(route)) return [`${brand} berendezések javítása és karbantartása`, `${brand} equipment repair and maintenance`]
  return [`${brand} berendezések műszaki támogatása, javítása és alkatrészellátása`, `${brand} equipment technical support, repair and parts supply`]
}

export type HubGuide = { brand: Pair; applications: Pair; services: Pair[] }
export const hubGuides: Partial<Record<Route, HubGuide>> = {
    metso: { brand: ['Metso törőgépek', 'Metso crushers'], applications: ['Kőbányai, aggregátum-előállítási, bányászati és újrahasznosítási folyamatokban a törési fokozatok, az anyagáram és az elvárt szemcsealak határozza meg a gépválasztást.', 'In quarrying, aggregate production, mining and recycling, the crushing stages, material flow and required particle shape determine the equipment selection.'], services: [['Állapotfelmérés, hibakeresés és tervezett karbantartás', 'Condition assessment, troubleshooting and planned maintenance'], ['Kopóalkatrészek és gépészeti alkatrészek azonosítása', 'Identification of wear parts and mechanical components'], ['Mechanikus, hidraulikus, villamos és vezérléstechnikai javítás', 'Mechanical, hydraulic, electrical and control-system repair']] },
    mj: { brand: ['M&J Recycling aprítógépek', 'M&J Recycling shredders'], applications: ['Előaprítás és finomaprítás kommunális, ipari, fa-, építési és egyéb hulladékáramokban. A megfelelő aprítási folyamat kialakításánál az anyagösszetétel, az elvárt frakció és a további válogatási vagy hasznosítási lépés is lényeges.', 'Pre-shredding and fine-shredding of municipal, industrial, wood, construction and other waste streams. Material composition, the required fraction and downstream sorting or recovery steps all matter when setting up the process.'], services: [['Megelőző karbantartás és üzemzavar-elhárítás', 'Preventive maintenance and breakdown support'], ['Vágóasztalok, kések és kopófelületek javítása, hardfacing', 'Repair and hardfacing of cutting tables, knives and wear surfaces'], ['Mechanikus, hidraulikus, villamos és vezérléstechnikai szerviz', 'Mechanical, hydraulic, electrical and control-system service']] },
    mfl: { brand: ['MFL törőberendezések', 'MFL crushing equipment'], applications: ['Régebbi MFL ásványfeldolgozó és törőgépek üzemeltetésénél kiemelten fontos a meglévő gépkivitel pontos felmérése. A rendelkezésre álló dokumentáció, az alkatrész mintája és a beépítési környezet alapján lehet biztonsággal meghatározni a következő lépést.', 'When operating older MFL mineral-processing and crushing machinery, it is particularly important to assess the exact existing configuration. The available documentation, a part sample and the installation environment make it possible to determine the right next step.'], services: [['MFL gépek és alkatrészek műszaki azonosítása', 'Technical identification of MFL equipment and components'], ['Javítási és felújítási lehetőségek felmérése', 'Assessment of repair and refurbishment options'], ['Alkatrészellátási igények egyeztetése', 'Coordination of parts-supply requirements']] },
    outotec: { brand: ['Outotec berendezések', 'Outotec equipment'], applications: ['Az Outotec névhez kötődő technológiák tipikusan ásványfeldolgozási és anyagkezelési feladatokban jelennek meg. A támogatás során a berendezés konkrét termékcsoportját, gyári azonosítóját és az üzemi feladatot érdemes először tisztázni.', 'Technologies associated with the Outotec name are typically used in mineral-processing and material-handling duties. It is best to first establish the specific product group, factory identification and operating duty.'], services: [['Műszaki egyeztetés és berendezésazonosítás', 'Technical consultation and equipment identification'], ['Karbantartási, hibakeresési és javítási támogatás', 'Maintenance, troubleshooting and repair support'], ['Alkatrész- és szervizigény felmérése', 'Assessment of parts and service requirements']] },
}

export type Intent = { kicker: Pair; title: Pair; lead: Pair; listTitle: Pair; bullets: Pair[]; body: { h: Pair; p: Pair }[]; note?: Pair; sources?: Pair[] }
export const intents: Partial<Record<Route, Intent>> = {
  metsoService: {
    kicker: ['Metso · Szerviz', 'Metso · Service'], title: ['Metso törőgép javítás és karbantartás', 'Metso crusher repair and maintenance'],
    lead: ['Helyszíni hibakeresés, megelőző karbantartás és javítás Metso pofás, kúpos, HSI és VSI törőberendezéseken. A gépet rendszerként vizsgáljuk: mechanika, hidraulika, villamosság és vezérléstechnika együtt adja a működő törőt.', 'On-site troubleshooting, preventive maintenance and repair on Metso jaw, cone, HSI and VSI crushers. We assess the machine as a complete system: mechanics, hydraulics, electrics and controls together deliver a reliable crusher.'],
    listTitle: ['Mit végzünk el?', 'What we carry out'],
    bullets: [['Állapotfelmérés és megelőző karbantartás üzemóra és kopásállapot alapján', 'Condition assessment and preventive maintenance based on operating hours and wear condition'], ['Helyszíni hibakeresés üzemzavar esetén, a hiba okának visszakeresésével', 'On-site troubleshooting during breakdowns, tracing the root cause of the fault'], ['Mechanikus javítás: csapágyak, tengelyek, hajtások és kopóelemek cseréje', 'Mechanical repair: bearings, shafts, drives and wear parts'], ['Hidraulikus javítás: nyomás- és működésvizsgálat, szelepek, munkahengerek, szivattyúk', 'Hydraulic repair: pressure and functional testing, valves, cylinders, pumps'], ['Villamos javítás: kábelezés, érzékelők, beavatkozók és tápellátás', 'Electrical repair: wiring, sensors, actuators and power supply'], ['PLC és CAN diagnosztika: vezérlés, I/O, CANopen és J1939 kommunikáció', 'PLC and CAN diagnostics: controls, I/O, CANopen and J1939 communication']],
    body: [{ h: ['Stacionárius és mobil kivitel', 'Stationary and mobile configurations'], p: ['A Metso több törőcsaládot stacionárius, hordozható és mobil megoldásként is kínál. A mobil gépeknél a hajtás, a szállítószalagok és a gépre telepített vezérlés is a szerviz tárgya, ezért a hibakeresést mindig a teljes gépre értelmezzük.', 'Metso offers several crusher families as stationary, portable and mobile solutions. On mobile machines the drive, conveyors and on-board controls are also part of the service scope, so we always approach troubleshooting at whole-machine level.'] }, { h: ['Hogyan indul a munka?', 'How the work starts'], p: ['A megkeresést a berendezés adataiból indítjuk: típustábla vagy gyári szám, üzemóra, a hiba leírása és néhány fotó. Ezekből előre megbecsülhető, milyen alkatrészre és milyen szakemberre lesz szükség a kiszálláson.', 'We start every enquiry from the equipment data: nameplate or serial number, operating hours, a fault description and a few photos. From these we can estimate in advance which parts and which specialists the site visit will require.'] }],
  },
  metsoParts: {
    kicker: ['Metso · Alkatrész', 'Metso · Parts'], title: ['Metso alkatrész és kopóalkatrész', 'Metso parts and wear parts'],
    lead: ['Metso törőgépekhez kapcsolódó alkatrész- és kopóalkatrész-igény felmérése és beszerzése. Az azonosítás mindig a gép gyári adataiból és a keresett elem cikkszámából vagy fotójából indul.', 'Assessment and sourcing of parts and wear parts for Metso crushers. Identification always starts from the machine factory data and the part number or a photo of the required item.'],
    listTitle: ['Tipikus kopó- és alkatrészcsoportok', 'Typical wear and spare part groups'],
    bullets: [['Pofás törők kopóelemei, például törőpofák és oldallemezek', 'Wear parts for jaw crushers, such as jaw plates and cheek plates'], ['Kúpos törők kopóelemei, például törőkúp- és köpenyelemek', 'Wear parts for cone crushers, such as mantles and concaves'], ['Röpítőtörők kopóelemei, például ütőlécek és ütközőlemezek', 'Wear parts for impact crushers, such as blow bars and impact aprons'], ['Rosta- és osztályozófelületek', 'Screening and classifying surfaces'], ['Gépészeti alkatrészek: csapágyak, tömítések, hajtáselemek', 'Mechanical components: bearings, seals and drive elements'], ['Hidraulikus és villamos alkatrészek, érzékelők', 'Hydraulic and electrical components, sensors']],
    body: [{ h: ['Miért az azonosítással kezdjük?', 'Why we start with identification'], p: ['Ugyanaz a gépcsalád több kivitelben és több gyártási évjáratban is előfordul, ezért a márkanév és a géptípus önmagában nem elég. A típustábla, a gyári szám és a kopott alkatrész fotója vagy mintadarabja alapján lényegesen kisebb a hibás rendelés kockázata.', 'The same crusher family exists in several configurations and production years, so the brand and machine type alone are not enough. Working from the nameplate, serial number and a photo or sample of the worn part substantially reduces the risk of ordering the wrong item.'] }, { h: ['Kopóalkatrész vagy felújítás?', 'Replacement wear part or refurbishment?'], p: ['Bizonyos kopófelületek feltöltő hegesztéssel is helyreállíthatók, ami sok esetben gyorsabb és költséghatékonyabb a teljes cserénél. Az állapot ismeretében megmondjuk, melyik út járható az adott alkatrésznél.', 'Some wear surfaces can be restored by rebuild welding, which is often faster and more economical than full replacement. Once we know the condition we advise which route is viable for that specific part.'] }],
  },
  mjService: {
    kicker: ['M&J Recycling · Szerviz', 'M&J Recycling · Service'], title: ['M&J aprítógép javítás és hardfacing', 'M&J shredder repair and hardfacing'],
    lead: ['M&J Recycling elő- és finomaprítók megelőző karbantartása, hibakeresése és javítása, valamint a vágóasztalok és kések hardfacing feltöltő hegesztése. Szervizcsapatunk gyártói képzést kapott az M&J dániai szakembereitől.', 'Preventive maintenance, troubleshooting and repair of M&J Recycling pre-shredders and fine-shredders, plus hardfacing rebuild welding of cutting tables and knives. Our service team was trained by M&J specialists in Denmark.'],
    listTitle: ['Mit végzünk el?', 'What we carry out'],
    bullets: [['Megelőző karbantartás és időszakos állapotellenőrzés', 'Preventive maintenance and periodic condition checks'], ['Üzemzavar-elhárítás és hibakeresés a teljes gépen', 'Breakdown support and troubleshooting across the whole machine'], ['Vágóasztalok, kések és kopófelületek javítása, hardfacing feltöltő hegesztése', 'Repair and hardfacing rebuild welding of cutting tables, knives and wear surfaces'], ['Mechanikus javítás: rotor, hajtás, csapágyazás, kopóelemek', 'Mechanical repair: rotor, drive, bearings and wear parts'], ['Hidraulikus javítás és a hidraulikus hajtáslánc vizsgálata', 'Hydraulic repair and inspection of the hydraulic drivetrain'], ['Villamos és vezérléstechnikai javítás, az eDrive gépek elektromos hajtásláncával együtt', 'Electrical and control-system repair, including the electric drivetrain on eDrive machines']],
    body: [{ h: ['Hardfacing: helyreállítás csere helyett', 'Hardfacing: restoration instead of replacement'], p: ['A vágóasztalok és kések kopott felületére kemény, kopásálló réteget hegesztünk fel, így az alkatrész geometriája visszaállítható teljes csere nélkül. Ez az egyik kiemelt szakterületünk, többéves gyakorlati tapasztalattal.', 'We deposit a hard, wear-resistant layer onto the worn surfaces of cutting tables and knives, restoring the component geometry without full replacement. This is one of our core specialisms, backed by several years of practical experience.'] }, { h: ['Gyártói ismeret, helyszíni tapasztalat', 'Manufacturer knowledge, on-site experience'], p: ['A négyfős, műszaki végzettségű csapat közvetlenül az M&J Recycling dániai szakembereinél szerzett képzést. A hibakeresést és a javítást egy kézben tartjuk, így a mechanikai, hidraulikus és villamos okok nem külön szolgáltatóknál derülnek ki.', 'Our four-person, technically qualified team trained directly with M&J Recycling specialists in Denmark. We keep troubleshooting and repair under one roof, so mechanical, hydraulic and electrical causes are not diagnosed by separate providers.'] }],
  },
  mjParts: {
    kicker: ['M&J Recycling · Alkatrész', 'M&J Recycling · Parts'], title: ['M&J Recycling alkatrész és kések', 'M&J Recycling parts and knives'],
    lead: ['Előaprítókhoz és finomaprítókhoz kapcsolódó alkatrész-, kés- és kopóelemigény felmérése és beszerzése, a gép típusa és gyári száma alapján.', 'Assessment and sourcing of parts, knives and wear items for pre-shredders and fine-shredders, based on the machine type and serial number.'],
    listTitle: ['Tipikus alkatrészcsoportok', 'Typical part groups'],
    bullets: [['Aprítókések és késtartó elemek', 'Shredder knives and knife holders'], ['Vágóasztal-elemek és kopóbetétek', 'Cutting-table components and wear inserts'], ['Rotor- és hajtásoldali gépészeti alkatrészek', 'Mechanical components on the rotor and drive side'], ['Hidraulikus elemek: szelepek, munkahengerek, tömítések', 'Hydraulic items: valves, cylinders and seals'], ['Villamos alkatrészek, érzékelők és vezérlési elemek', 'Electrical parts, sensors and control components'], ['Kopásálló hegesztőanyagok a hardfacing helyreállításhoz', 'Wear-resistant welding consumables for hardfacing restoration']],
    body: [{ h: ['Késcsere vagy késfelújítás?', 'Knife replacement or knife rebuild?'], p: ['A kések és a vágóasztal kopása gyakran feltöltő hegesztéssel is kezelhető, nem minden esetben szükséges új alkatrész. A kopás mértékének felmérése után javaslatot adunk arra, hogy a csere vagy a felújítás gazdaságosabb.', 'Wear on knives and the cutting table can often be addressed by rebuild welding, so a new part is not always necessary. After assessing the extent of wear we advise whether replacement or rebuilding is more economical.'] }, { h: ['Mit érdemes elküldeni?', 'What to send us'], p: ['A gép típusa és gyári száma, a keresett elem cikkszáma vagy fotója, valamint a kopott felületről készült képek. Ha van rá lehetőség, a kopott alkatrész mintadarabja is segít.', 'The machine type and serial number, the part number or a photo of the required item, and images of the worn surface. Where possible, a sample of the worn part also helps.'] }],
  },
  mflService: {
    kicker: ['MFL · Szerviz', 'MFL · Service'], title: ['MFL törőgép javítás és felújítás', 'MFL crusher repair and refurbishment'],
    lead: ['Régi Maschinenfabrik Liezen – MFL – törő- és ásványfeldolgozó berendezések javítása, felújítása és vezérléskorszerűsítése. A munkát minden esetben a meglévő gépkivitel pontos felmérésével kezdjük.', 'Repair, refurbishment and control-system modernisation of legacy Maschinenfabrik Liezen — MFL — crushing and mineral-processing equipment. We always begin by accurately surveying the existing configuration.'],
    listTitle: ['Mit végzünk el?', 'What we carry out'],
    bullets: [['Helyszíni állapotfelmérés és a meglévő gépkivitel dokumentálása', 'On-site condition assessment and documentation of the existing configuration'], ['Mechanikus javítás és kopott részegységek helyreállítása', 'Mechanical repair and restoration of worn assemblies'], ['Hidraulikus és villamos rendszerek hibakeresése és javítása', 'Troubleshooting and repair of hydraulic and electrical systems'], ['Vezérléskorszerűsítés: PLC, kezelői kijelző, I/O, szenzorika, kábelezés', 'Control modernisation: PLC, operator display, I/O, sensors and wiring'], ['CAN, CANopen és J1939 alapú kommunikáció kiépítése vagy cseréje', 'Implementation or replacement of CAN, CANopen and J1939 communication'], ['Javítási és felújítási lehetőségek reális felmérése gépcsere előtt', 'A realistic assessment of repair and refurbishment options before replacing the machine']],
    body: [{ h: ['Amikor a mechanika még jó', 'When the mechanics are still sound'], p: ['Ha a gép mechanikailag rendben van, az elavult vagy már nem támogatott vezérlés önmagában nem indokolja a gépcserét. Ilyen esetben a részleges vagy teljes retrofit gyakran gazdaságosabb. Az egyik alkalmazott platform az ifm ecomatmobile, amely mobil gépekhez készült vezérlőket, kijelzőket, I/O modulokat és érzékelőket kínál.', 'If the machine is mechanically sound, an obsolete or unsupported control system alone does not justify replacement. In such cases a partial or complete retrofit is often more economical. One platform we use is ifm ecomatmobile, which provides controllers, displays, I/O modules and sensors for mobile machinery.'] }, { h: ['Dokumentáció nélkül is', 'Even without documentation'], p: ['A régi MFL gépparknál gyakran hiányos a dokumentáció. Ilyenkor a típustáblából, a helyszíni felmérésből és a beépítési környezetből építjük fel a szükséges műszaki adatokat, és csak ezután adunk javaslatot.', 'Documentation is often incomplete on older MFL fleets. In that case we build up the required technical data from the nameplate, an on-site survey and the installation environment, and only then make a recommendation.'] }],
    note: ['A végleges pofás / kúpos / röpítő / VSI típuslistát csak régi MFL katalógus vagy más elsődleges dokumentáció birtokában tesszük fel tényként.', 'A definitive list of jaw, cone, impact and VSI models will only be published as fact once an original MFL catalogue or equivalent primary documentation is available.'],
    sources: [['ifm ecomatmobile', 'https://www.ifm.com/hu/hu/shared/technologien/ecomatmobile/rendszerek-mobil-munkagepekhez'], ['Maschinenfabrik Liezen und Gießerei', 'https://www.mfl.at/en/']],
  },
  mflParts: {
    kicker: ['MFL · Alkatrész', 'MFL · Parts'], title: ['MFL törőgép alkatrész beszerzés', 'MFL crusher parts sourcing'],
    lead: ['Korábbi MFL berendezésekhez kapcsolódó alkatrész- és kopóalkatrész-igény azonosítása és beszerzése, akkor is, ha a gép dokumentációja hiányos.', 'Identification and sourcing of parts and wear parts for legacy MFL equipment, including cases where the machine documentation is incomplete.'],
    listTitle: ['Hogyan azonosítjuk az alkatrészt?', 'How we identify the part'],
    bullets: [['Azonosítás típustábla, gyári szám és helyszíni felmérés alapján', 'Identification from the nameplate, serial number and an on-site survey'], ['Mintadarab vagy méretezett fotó alapján történő beazonosítás', 'Identification from a sample or a dimensioned photo'], ['Kopóelemek és gépészeti alkatrészek igényének felmérése', 'Assessment of wear items and mechanical component requirements'], ['Méretfelvétel a beépítési helyen, ha nincs meg a rajz', 'Dimensional survey at the installation point where no drawing exists'], ['Javítható és cserélendő elemek szétválasztása', 'Separating items that can be repaired from those needing replacement'], ['Alkatrészellátási igények egyeztetése és ajánlatadás', 'Coordination of parts-supply requirements and quotation']],
    body: [{ h: ['Miért az azonosítás a leglassabb lépés?', 'Why identification is the slowest step'], p: ['A régi gépeknél ugyanaz a géptípus több kivitelben is előfordulhat, és az évek során beépített javítások is módosíthatták az eredeti állapotot. A pontos azonosítás ezért időt igényel, de nélküle nagy a hibás rendelés kockázata.', 'On older machines the same type may exist in several configurations, and repairs carried out over the years may have altered the original state. Accurate identification therefore takes time, but without it the risk of ordering the wrong item is high.'] }, { h: ['Mi segít a leginkább?', 'What helps most'], p: ['A típustábla fotója, a gyári szám, a kopott alkatrész mintadarabja vagy méretezett fotója, valamint a beépítési helyről készült képek. Ha maradt bármilyen régi dokumentáció vagy rajz, az jelentősen gyorsítja a folyamatot.', 'A photo of the nameplate, the serial number, a sample or dimensioned photo of the worn part, and images of the installation point. Any surviving old documentation or drawing speeds the process up considerably.'] }],
    note: ['A végleges pofás / kúpos / röpítő / VSI típuslistát csak régi MFL katalógus vagy más elsődleges dokumentáció birtokában tesszük fel tényként.', 'A definitive list of jaw, cone, impact and VSI models will only be published as fact once an original MFL catalogue or equivalent primary documentation is available.'],
    sources: [['Maschinenfabrik Liezen und Gießerei', 'https://www.mfl.at/en/']],
  },
  outotecService: {
    kicker: ['Outotec · Szerviz', 'Outotec · Service'], title: ['Outotec szerviz és karbantartás', 'Outotec service and maintenance'],
    lead: ['Outotec berendezésekhez kapcsolódó helyszíni karbantartás, hibakeresés és javítás Magyarországon. A támogatást a berendezés termékcsoportjának és gyári azonosítójának tisztázásával kezdjük.', 'On-site maintenance, troubleshooting and repair for Outotec equipment in Hungary. We begin support by establishing the equipment’s product group and factory identification.'],
    listTitle: ['Mit végzünk el?', 'What we carry out'],
    bullets: [['Műszaki egyeztetés és a berendezés azonosítása', 'Technical consultation and equipment identification'], ['Megelőző karbantartás és időszakos ellenőrzés', 'Preventive maintenance and periodic inspection'], ['Hibakeresés és üzemzavar-elhárítás', 'Troubleshooting and breakdown support'], ['Mechanikus és hidraulikus javítás', 'Mechanical and hydraulic repair'], ['Villamos és vezérléstechnikai javítás, PLC és CAN diagnosztika', 'Electrical and control-system repair, PLC and CAN diagnostics'], ['Szervizigény felmérése és a következő lépés meghatározása', 'Assessment of service requirements and definition of the next step']],
    body: [{ h: ['Ásványfeldolgozás és anyagkezelés', 'Mineral processing and material handling'], p: ['Az Outotec névhez kötődő technológiák tipikusan ásványfeldolgozási és anyagkezelési feladatokban jelennek meg. Az üzemi feladat, a feldolgozott anyag és a berendezés kivitele együtt határozza meg, milyen karbantartási ciklus és milyen javítás indokolt.', 'Technologies associated with the Outotec name are typically used in mineral-processing and material-handling duties. The operating duty, the processed material and the equipment configuration together determine the appropriate maintenance cycle and repair scope.'] }, { h: ['Egy kézben a hiba és a megoldás', 'Fault and solution under one roof'], p: ['A mechanikus, hidraulikus, villamos és vezérléstechnikai munkát ugyanaz a csapat végzi, így a hiba feltárása és a javítás nem külön szolgáltatóknál zajlik.', 'Mechanical, hydraulic, electrical and control-system work is carried out by the same team, so diagnosis and repair do not sit with separate providers.'] }],
    note: ['Amennyiben a képviseleti szerződés meghatározott termékcsoportokra korlátozódik, a termékkört név szerint is érdemes felsorolni.', 'If the representation agreement is limited to defined product groups, the applicable product range should be listed by name.'],
  },
  outotecParts: {
    kicker: ['Outotec · Alkatrész', 'Outotec · Parts'], title: ['Outotec alkatrész beszerzés', 'Outotec parts sourcing'],
    lead: ['Outotec berendezésekhez kapcsolódó alkatrész- és kopóalkatrész-igény felmérése és beszerzése, a berendezés gyári azonosítása alapján.', 'Assessment and sourcing of parts and wear parts for Outotec equipment, based on factory identification of the machine.'],
    listTitle: ['Mit mérünk fel?', 'What we assess'],
    bullets: [['Berendezés és termékcsoport azonosítása', 'Identification of the equipment and product group'], ['Kopóalkatrészek igényének felmérése', 'Assessment of wear-part requirements'], ['Gépészeti alkatrészek: csapágyak, tömítések, hajtáselemek', 'Mechanical components: bearings, seals and drive elements'], ['Hidraulikus és villamos alkatrészek, érzékelők', 'Hydraulic and electrical components, sensors'], ['Alkatrész- és szervizigény összehangolása', 'Alignment of parts and service requirements'], ['Ajánlatadás a beazonosított elemekre', 'Quotation for the identified items']],
    body: [{ h: ['Az azonosítás a kiindulópont', 'Identification is the starting point'], p: ['Az alkatrészigényt akkor tudjuk pontosan felmérni, ha ismert a berendezés konkrét termékcsoportja és gyári azonosítója. Ez a lépés a márkanév vállalati hátterének változásai miatt is fontos.', 'We can only assess the parts requirement accurately once the specific product group and factory identification of the equipment are known. This step also matters because of the changes in the brand’s corporate background.'] }, { h: ['Alkatrész és szerviz együtt', 'Parts and service together'], p: ['Sok esetben az alkatrészcsere és a javítás egy munkafolyamat. Ha a kopás oka gépészeti vagy vezérlési probléma, az alkatrész cseréje önmagában nem tartós megoldás, ezért ezeket együtt vizsgáljuk.', 'Parts replacement and repair are often a single workflow. If the wear is caused by a mechanical or control problem, replacing the part alone is not a lasting solution, so we examine them together.'] }],
    note: ['Amennyiben a képviseleti szerződés meghatározott termékcsoportokra korlátozódik, a termékkört név szerint is érdemes felsorolni.', 'If the representation agreement is limited to defined product groups, the applicable product range should be listed by name.'],
  },
}
export const siblingOf: Partial<Record<Route, Route>> = { metsoService: 'metsoParts', metsoParts: 'metsoService', mjService: 'mjParts', mjParts: 'mjService', mflService: 'mflParts', mflParts: 'mflService', outotecService: 'outotecParts', outotecParts: 'outotecService' }
export const intentsOf: Partial<Record<Route, [Route, Route]>> = { metso: ['metsoService', 'metsoParts'], mj: ['mjService', 'mjParts'], mfl: ['mflService', 'mflParts'], outotec: ['outotecService', 'outotecParts'] }
export function intentLinksFor(route: Route): [Route, Pair][] {
  const pair = intentsOf[route]
  const links: [Route, Pair][] = pair ? pair.map((item) => [item, relatedLabel(item)] as [Route, Pair]) : []
  links.push(['service', ['Szerviz és retrofit szolgáltatások', 'Service and retrofit capabilities']], ['contact', ['Kapcsolat és ajánlatkérés', 'Contact and enquiries']])
  return links
}
export function relatedLabel(route: Route): Pair {
  const brand = brandOf[route] ?? ''
  if (partsRoutes.includes(route)) return [`${brand} alkatrész és kopóalkatrész`, `${brand} parts and wear parts`]
  if (serviceRoutes.includes(route)) return [`${brand} javítás és karbantartás`, `${brand} repair and maintenance`]
  return [`${brand} áttekintés`, `${brand} overview`]
}

export type PageHead = { kicker: Pair; title: Pair; lead: Pair }
export const pageHeads: Record<Route, PageHead> = {
  // `|` marks the headline line break; the rendered h1 and the static h1 must produce identical text.
  home: { kicker: ['Geinvest Kft.', 'Geinvest Kft.'], title: ['Gépek. Alkatrészek.|Szerviz. Megoldások.', 'Machines. Parts.|Service. Solutions.'], lead: ['Ipari, kőfeldolgozó és hulladék-újrahasznosító berendezések kereskedelme, alkatrészellátása, javítása és korszerűsítése.', 'Trading, parts supply, repair and modernisation of industrial, quarrying and waste-recycling equipment.'] },
  brands: { kicker: ['Berendezések', 'Equipment'], title: ['Márkák és technológiák', 'Brands and technologies'], lead: ['Az alábbi oldalakon röviden bemutatjuk azokat a gyártókat és gépcsoportokat, amelyekkel a Geinvest munkája során rendszeresen foglalkozik.', 'The following pages introduce the manufacturers and equipment groups that Geinvest works with on a regular basis.'] },
  service: { kicker: ['Szerviz & Retrofit', 'Service & Retrofit'], title: ['Hibakeresés, javítás és korszerűsítés', 'Troubleshooting, repair and modernisation'], lead: ['A berendezés problémáját rendszerben vizsgáljuk: mechanika, hidraulika, villamosság és vezérléstechnika együtt adja a működő gépet.', 'We assess equipment as a complete system: mechanics, hydraulics, electrics and control engineering all contribute to a reliable machine.'] },
  references: { kicker: ['Referenciák', 'References'], title: ['Elvégzett munkák', 'Completed work'], lead: ['Ezt a részt a következő körben konkrét projektekből, saját fotókból és rövid műszaki leírásokból építjük fel.', 'In the next phase, this section will be developed with specific projects, original photographs and concise technical descriptions.'] },
  contact: { kicker: ['Kapcsolat', 'Contact'], title: ['Geinvest Kft.', 'Geinvest Kft.'], lead: ['Berendezés, alkatrész, szerviz vagy retrofit igény esetén keressen bennünket közvetlenül.', 'Contact us directly for equipment, parts, service or retrofit requirements.'] },
  metso: { kicker: ['Metso', 'Metso'], title: ['Töréstechnika több mint egy évszázados háttérrel', 'Crushing technology backed by more than a century of expertise'], lead: ['A Metso jelenlegi kínálatában stacionárius és mobil törési megoldások találhatók aggregátum-, bányászati és újrahasznosítási alkalmazásokhoz.', 'Metso’s current portfolio includes stationary and mobile crushing solutions for aggregates, mining and recycling applications.'] },
  mj: { kicker: ['Magyarországi képviselet és szerviz', 'Hungarian representation and service'], title: ['M&J Recycling', 'M&J Recycling'], lead: ['Nagyteljesítményű hulladékaprító berendezések, gyártói szervizismerettel és magyarországi műszaki háttérrel.', 'High-capacity waste-shredding equipment backed by manufacturer service knowledge and Hungarian technical support.'] },
  mfl: { kicker: ['Maschinenfabrik Liezen', 'Maschinenfabrik Liezen'], title: ['A klasszikus MFL berendezések támogatása', 'Support for legacy MFL equipment'], lead: ['Itt kifejezetten a régi Maschinenfabrik Liezen – MFL – berendezésekről beszélünk, nem az SBM mai termékportfóliójáról.', 'This page specifically concerns older Maschinenfabrik Liezen — MFL — equipment, rather than the current SBM product portfolio.'] },
  outotec: { kicker: ['Magyarországi képviselet és szerviz', 'Hungarian representation and service'], title: ['Outotec', 'Outotec'], lead: ['A Geinvest Kft. az Outotec termékek magyarországi képviseletét és teljes körű szervizét biztosítja.', 'Geinvest Kft. provides Hungarian representation and comprehensive service for Outotec products.'] },
  metsoService: intentHead('metsoService'), metsoParts: intentHead('metsoParts'), mjService: intentHead('mjService'), mjParts: intentHead('mjParts'), mflService: intentHead('mflService'), mflParts: intentHead('mflParts'), outotecService: intentHead('outotecService'), outotecParts: intentHead('outotecParts'),
}
function intentHead(route: Route): PageHead { const item = intents[route]!; return { kicker: item.kicker, title: item.title, lead: item.lead } }

export const ogImage = `${origin}/assets/img/home/metso-quarry.jpg`
const navRoutes: Route[] = ['home', 'brands', 'service', 'references', 'contact']

/** Schema.org @graph for a page. Shared by the runtime head updater and the build-time HTML injector. */
export function structuredData(route: Route, locale: Locale): Record<string, unknown> {
  const [name, description] = meta[locale][route]
  const pageUrl = `${origin}${paths[locale][route]}`
  const inLanguage = locale === 'hu' ? 'hu-HU' : 'en'
  const brand = brandOf[route]
  const parent = parentOf[route]
  const crumbs: Record<string, unknown>[] = [{ '@type': 'ListItem', position: 1, name: locale === 'hu' ? 'Főoldal' : 'Home', item: `${origin}${paths[locale].home}` }]
  if (parent && brand) crumbs.push({ '@type': 'ListItem', position: 2, name: brand, item: `${origin}${paths[locale][parent]}` })
  crumbs.push({ '@type': 'ListItem', position: crumbs.length + 1, name, item: pageUrl })
  const graph: Record<string, unknown>[] = [
    { '@type': ['Organization', 'LocalBusiness'], '@id': `${origin}/#organization`, name: 'Geinvest Kft.', url: origin, logo: `${origin}/favicon.png`, telephone: phone, email, address: { '@type': 'PostalAddress', streetAddress: 'Petőfi utca 1/C.', postalCode: '2181', addressLocality: 'Iklad', addressCountry: 'HU' }, areaServed: { '@type': 'Country', name: 'Hungary' } },
    { '@type': 'WebSite', '@id': `${origin}/#website`, url: origin, name: 'Geinvest Kft.', publisher: { '@id': `${origin}/#organization` }, inLanguage: ['hu-HU', 'en'] },
    { '@type': 'WebPage', '@id': `${pageUrl}#webpage`, url: pageUrl, name, description, inLanguage, isPartOf: { '@id': `${origin}/#website` }, breadcrumb: { '@id': `${pageUrl}#breadcrumb` } },
    { '@type': 'BreadcrumbList', '@id': `${pageUrl}#breadcrumb`, itemListElement: crumbs },
  ]
  if (brand) graph.push({ '@type': 'Service', '@id': `${pageUrl}#service`, name, description, url: pageUrl, provider: { '@id': `${origin}/#organization` }, areaServed: { '@type': 'Country', name: 'Hungary' }, serviceType: tx(locale, ...serviceTypeOf(route, brand)) })
  const items = faqs[route]
  if (items?.length) graph.push({ '@type': 'FAQPage', '@id': `${pageUrl}#faq`, inLanguage, mainEntity: items.map((item) => ({ '@type': 'Question', name: tx(locale, ...item.q), acceptedAnswer: { '@type': 'Answer', text: tx(locale, ...item.a) } })) })
  return { '@context': 'https://schema.org', '@graph': graph }
}

const escapes: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }
function esc(value: string) { return value.replace(/[&<>"]/g, (character) => escapes[character]) }

/** Head tags for a page. `depth` is how many directories deep the HTML file sits, for the relative favicon. */
export function headTags(route: Route, locale: Locale, depth: number): string {
  const [title, description] = meta[locale][route]
  const canonical = `${origin}${paths[locale][route]}`
  const favicon = `${'../'.repeat(depth) || './'}favicon.png`
  return [
    `<title>${esc(title)}</title>`,
    `<meta name="description" content="${esc(description)}" />`,
    `<link rel="canonical" href="${canonical}" />`,
    `<link rel="alternate" hreflang="hu" href="${origin}${paths.hu[route]}" />`,
    `<link rel="alternate" hreflang="en" href="${origin}${paths.en[route]}" />`,
    `<link rel="alternate" hreflang="x-default" href="${origin}${paths.hu[route]}" />`,
    `<meta property="og:title" content="${esc(title)}" />`,
    `<meta property="og:description" content="${esc(description)}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:url" content="${canonical}" />`,
    `<meta property="og:image" content="${ogImage}" />`,
    `<meta property="og:locale" content="${locale === 'en' ? 'en_US' : 'hu_HU'}" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<link rel="icon" type="image/png" href="${favicon}" />`,
    `<script type="application/ld+json">${JSON.stringify(structuredData(route, locale)).replace(/</g, '\\u003c')}</script>`,
  ].join('\n    ')
}

/**
 * Crawlable page content placed inside #root. React clears the container on mount, so this is a
 * no-JS fallback and a complete copy of the page's key text for crawlers that do not execute JS.
 */
export function staticBody(route: Route, locale: Locale): string {
  const t = (pair: Pair) => esc(tx(locale, ...pair))
  const head = pageHeads[route]
  const intent = intents[route]
  const guide = hubGuides[route]
  const items = faqs[route]
  const parts: string[] = [`<div class="page-head"><div class="container"><p class="kicker">${t(head.kicker)}</p><h1>${t(head.title).replace('|', '<br />')}</h1><p>${t(head.lead)}</p></div></div>`]
  const body: string[] = []
  if (intent) {
    body.push(`<h2>${t(intent.listTitle)}</h2><ul>${intent.bullets.map((bullet) => `<li>${t(bullet)}</li>`).join('')}</ul>`)
    body.push(intent.body.map((block) => `<h2>${t(block.h)}</h2><p>${t(block.p)}</p>`).join(''))
    if (intent.note) body.push(`<p>${t(intent.note)}</p>`)
  }
  if (guide) {
    body.push(`<h2>${tx(locale, 'Szerviz, alkatrész és műszaki támogatás', 'Service, parts and technical support')}</h2><p>${t(guide.applications)}</p>`)
    body.push(`<h2>${tx(locale, 'Miben tudunk segíteni?', 'How we can help')}</h2><ul>${guide.services.map((service) => `<li>${t(service)}</li>`).join('')}</ul>`)
  }
  if (!intent && !guide) body.push(`<p>${esc(meta[locale][route][1])}</p>`)
  if (items?.length) body.push(`<h2>${tx(locale, 'Gyakori kérdések', 'Frequently asked questions')}</h2>${items.map((item) => `<h3>${t(item.q)}</h3><p>${t(item.a)}</p>`).join('')}`)
  const links = [...new Set([...navRoutes, ...(intentsOf[route] ?? []), ...(parentOf[route] ? [parentOf[route]!] : []), ...(siblingOf[route] ? [siblingOf[route]!] : []), ...brandHubRoutes])].filter((item) => item !== route)
  body.push(`<h2>${tx(locale, 'Oldalak', 'Pages')}</h2><ul>${links.map((item) => `<li><a href="${paths[locale][item]}">${esc(meta[locale][item][0].split(' | ')[0])}</a></li>`).join('')}</ul>`)
  parts.push(`<div class="section"><div class="container prose">${body.join('')}</div></div>`)
  return parts.join('\n      ')
}
